config/routes.rb
EmployeesManager::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resource :user, only: [:edit, :show, :update]

  root :to => 'admin/dashboard#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :team_members
  has_many :users, through: :team_members
  accepts_nested_attributes_for :team_members, allow_destroy: true

  validates_presence_of :name
  validate :must_have_members

  private

  def must_have_members
    if team_members.empty? or team_members.all? {|member| member.marked_for_destruction? }
      errors[:base] << "Must have at least one member"
    end
  end
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :email, :mobile, :phone, :twitter, :facebook
  validates_length_of :mobile, in: 10..32
  validates_length_of :phone, in: 7..32
  validates :mobile, format: {with: /\+?(\d|\s)+$/}
  validates :phone, format: {with: /\+?(\d|\s)+$/}
  validates :email, uniqueness: true, format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :facebook, format: {with: /facebook.com\/\w+/}
  validate :valid_twitter?

  has_many :team_members
  has_many :teams, through: :team_members

  before_save :set_profile_picture

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"]
      end
    end
  end

  def password_required?
    false
  end

  private

  def valid_twitter?
    name = twitter.scan(/(\w+)$/).join if twitter
    if name.present?
      begin
        user = Twitter.user(name)
      rescue Exception => e
        errors.add(:twitter, "does not exists")
      end
    end
  end

  def set_profile_picture
    name = twitter.scan(/(\w+)$/).join
    user = Twitter.user(name)
    self.profile_picture = user.profile_image_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      user_path
    else
      admin_dashboard_path
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
   def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.present?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:error] = "User does not exist"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate_user!
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to user_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head>
    %title> Employees Manager
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

%body
  .flash
    %p.notice= notice
    %p.alert= flash[:error]
  .content
    = yield

app/views/users/edit.html.haml
%h1 Edit Your Profile
=form_for @user, html: {class: "user_form"} do |f|
  %p
    =f.label :name
    =f.text_field :name, class: "text"
  %p
    =f.label :email
    =f.text_field :email, class: "text"
  %p
    =f.label :phone
    =f.text_field :phone, class: "text"
  %p
    =f.label :mobile
    =f.text_field :mobile, class: "text"
  %p
    =f.label :facebook
    =f.text_field :facebook, class: "text"
  %p
    =f.label :twitter
    =f.text_field :twitter, class: "text"
  %p
    =f.submit
.links
  =link_to "Back", :back

app/views/users/show.html.haml
%h1 Your Profile
.pic
  =image_tag @user.profile_picture
.info
  %p
    Name:
    =@user.name
  %p
    Email
    =@user.email
  %p
    Phone
    =@user.phone
  %p
    Mobile
    =@user.mobile
  %p
    Twitter
    =@user.twitter
  %p
    Facebook
    =@user.facebook
.links
  =link_to "Edit", edit_user_path
  =link_to "Logout", destroy_user_session_path, method: :delete